os: linux
language: node_js
services:
  - docker
  
deploy: 
  provider: elasticbeanstalk
  region: us-east-2
  app: image-searcher
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-2-991075679647
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

