os: linux
language: node_js
services:
  - docker

script:
    - docker build -t antoniuk02/image-searcher-angular ./fe-image-searcher
    - docker build -t antoniuk02/image-searcher-nest ./image-searcher
    - docker build -t antoniuk02/image-searcher-nginx ./nginx
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push antoniuk02/image-searcher-angular
    - docker push antoniuk02/image-searcher-nest
    - docker push antoniuk02/image-searcher-nginx
  
deploy: 
  provider: elasticbeanstalk
  region: us-east-2
  app: image-searcher
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-2-991075679647
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

